# Generated by Django 6.0.6 on 2026-06-17 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_networks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên chứng chỉ')),
                ('root_cert', models.FileField(upload_to='certificates/%Y/%m/', verbose_name='Root CA Certificate')),
                ('inter_cert', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/', verbose_name='Intermediate Certificate')),
                ('server_cert', models.FileField(upload_to='certificates/%Y/%m/', verbose_name='Server Certificate')),
                ('private_key', models.FileField(upload_to='certificates/%Y/%m/', verbose_name='Private Key')),
                ('status', models.CharField(choices=[('pending', 'Đang xử lý'), ('valid', 'Hợp lệ'), ('invalid', 'Không hợp lệ'), ('deployed', 'Đã deploy'), ('deploying', 'Đang deploy'), ('failed', 'Thất bại')], default='pending', max_length=20)),
                ('common_name', models.CharField(blank=True, max_length=255)),
                ('issuer', models.CharField(blank=True, max_length=500)),
                ('subject_alt_names', models.TextField(blank=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('validation_errors', models.TextField(blank=True)),
                ('deploy_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core_networks.domain', verbose_name='Domain')),
            ],
            options={
                'verbose_name': 'SSL Certificate',
                'verbose_name_plural': 'SSL Certificates',
                'ordering': ['-created_at'],
            },
        ),
    ]
