# Generated by Django 6.0.6 on 2026-06-19 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_manager', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('failed', 'Thất bại')], max_length=20, verbose_name='Kết quả')),
                ('log_snapshot', models.TextField(blank=True, verbose_name='Toàn bộ log của lần deploy này')),
                ('started_at', models.DateTimeField(verbose_name='Bắt đầu lúc')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc lúc')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploy_history', to='ssl_manager.sslcertificate', verbose_name='Chứng chỉ')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người kích hoạt')),
            ],
            options={
                'verbose_name': 'Lịch sử Deploy',
                'verbose_name_plural': 'Lịch sử Deploy',
                'ordering': ['-started_at'],
            },
        ),
    ]
