# Generated by Django 6.0.6 on 2026-06-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='subdomain',
            new_name='code',
        ),
    ]
