# Generated by Django 6.0.6 on 2026-06-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_rename_subdomain_tenant_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantuser',
            options={'verbose_name': 'Thành viên tổ chức', 'verbose_name_plural': 'Thành viên tổ chức'},
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='role',
            field=models.CharField(choices=[('tenant_admin', 'Quản trị tổ chức '), ('tenant_user', 'Nhân viên')], default='tenant_user', max_length=20, verbose_name='Quyền hạn'),
        ),
    ]
