# Generated by Django 6.0.6 on 2026-06-21 05:33

import apps.utils.encryption
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_rename_subdomain_tenant_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELKClusterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='Là cụm ELK dùng chung cho các Tenant không có cấu hình riêng')),
                ('name', models.CharField(max_length=100, verbose_name='Tên gợi nhớ')),
                ('hosts', models.CharField(help_text='Danh sách host ES, phân tách bằng dấu phẩy. Ví dụ: https://es1:9200,https://es2:9200', max_length=500, verbose_name='Elasticsearch Hosts')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='ES Username (tùy chọn)')),
                ('password', apps.utils.encryption.EncryptedTextField(blank=True, null=True, verbose_name='ES Password (đã mã hóa, tùy chọn)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elk_config', to='tenants.tenant', verbose_name='Tenant sở hữu (để trống nếu là cụm dùng chung)')),
            ],
            options={
                'verbose_name': 'Cấu hình cụm ELK',
                'verbose_name_plural': 'Cấu hình cụm ELK',
            },
        ),
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('cpu', 'CPU (%)'), ('ram', 'RAM (%)'), ('disk', 'Disk (%)'), ('queue', 'Mail Queue (số lượng)')], max_length=20, verbose_name='Chỉ số')),
                ('warning_threshold', models.FloatField(verbose_name='Ngưỡng Warning')),
                ('critical_threshold', models.FloatField(verbose_name='Ngưỡng Critical')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_thresholds', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Ngưỡng cảnh báo tùy biến',
                'verbose_name_plural': 'Ngưỡng cảnh báo tùy biến',
                'unique_together': {('tenant', 'metric')},
            },
        ),
    ]
