# Generated by Django 6.0.6 on 2026-06-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên Miền (ví dụ: domain.com)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
        migrations.CreateModel(
            name='ZimbraServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên server')),
                ('hostname', models.CharField(max_length=255, verbose_name='Hostname/IP')),
                ('port', models.IntegerField(default=22, verbose_name='SSH Port')),
                ('username', models.CharField(default='root', max_length=100, verbose_name='SSH User')),
                ('ssh_password', models.CharField(blank=True, max_length=255, verbose_name='SSH Password (Khuyến khích mã hóa)')),
                ('ssh_key', models.TextField(blank=True, verbose_name='SSH Private Key')),
                ('zimbra_home', models.CharField(default='/opt/zimbra', max_length=255, verbose_name='Zimbra Home')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zimbra Server',
                'verbose_name_plural': 'Zimbra Servers',
            },
        ),
    ]
