# Generated by Django 6.0.6 on 2026-06-17 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_networks', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='zimbraserver',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='tenants.tenant', verbose_name='Dedicated Tenant (Nếu có)'),
        ),
        migrations.AddField(
            model_name='domain',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='core_networks.zimbraserver', verbose_name='Zimbra Server phụ trách'),
        ),
    ]
