# Generated by Django 6.0.6 on 2026-06-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_networks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zimbraserver',
            name='zimbra_admin_email',
            field=models.EmailField(blank=True, help_text='Ví dụ: admin@yourdomain.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='zimbraserver',
            name='zimbra_admin_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
