# Generated by Django 6.0.6 on 2026-06-17 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_networks', '0003_zimbraserver_zimbra_admin_email_and_more'),
        ('tenants', '0002_rename_subdomain_tenant_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='tenants.tenant', verbose_name='Tenant'),
        ),
    ]
