# Generated by Django 6.0.6 on 2026-06-18 03:11

import apps.utils.encryption
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_networks', '0004_alter_domain_tenant'),
        ('tenants', '0002_rename_subdomain_tenant_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='zimbraserver',
            name='ssh_key',
            field=apps.utils.encryption.EncryptedTextField(blank=True, verbose_name='SSH Private Key (đã mã hóa)'),
        ),
        migrations.AlterField(
            model_name='zimbraserver',
            name='ssh_password',
            field=apps.utils.encryption.EncryptedTextField(blank=True, verbose_name='SSH Password (đã mã hóa)'),
        ),
        migrations.AlterField(
            model_name='zimbraserver',
            name='zimbra_admin_password',
            field=apps.utils.encryption.EncryptedTextField(blank=True, null=True, verbose_name='Zimbra Admin Password (đã mã hóa)'),
        ),
    ]
