# Generated by Django 6.0.6 on 2026-06-22 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_networks', '0005_alter_domain_tenant_alter_zimbraserver_ssh_key_and_more'),
        ('tenants', '0002_rename_subdomain_tenant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_created_on_zimbra',
            field=models.BooleanField(default=True, help_text='Nếu không chọn, Tên miền sẽ ko tạo trên máy chủ Email', verbose_name='Khởi tạo trên máy chủ Email'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='core_networks.zimbraserver', verbose_name='Máy chủ Email'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='tenants.tenant', verbose_name='Tổ chức '),
        ),
    ]
